buy/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from dynaconf import settings as _settings


urlpatterns = [
    path(_settings.ADMIN_URL, admin.site.urls),
    path('', include('buysite.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buysite/urls.py
from django.urls import path, re_path
from buysite import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView

urlpatterns = [
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('login/', LoginView.as_view(template_name='buysite/account/login.html'), name='login'),
    path('logout/',LogoutView.as_view(template_name='buysite/account/logout.html'),name = 'logout'),
    path('password-change/', PasswordChangeView.as_view(template_name='buysite/account/password_change_form.html'), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='buysite/account/password_change_done.html'), name='password_change_done'),
    
    path('', views.index, name='home'),
    path('ticket/<int:fp>', views.ticket, name='ticket'),
    path('personal/', views.personal, name='personal'),
    path('personal/nogroup/', views.personal, name='nogroup'),
    
    
    path('addbuy/', views.addbuy, name='addbuy'),
    path('editbuy/', views.editbuy, name='editbuy'),
    
    path('group/add/', views.addGroup, name='addgroup'),
    path('group/edit/', views.editGroup, name='editgroup'),
    path('group/<slug:group_slug>/', views.group, name='group'),
    
    path('category/<slug:category_slug>/', views.category, name='category'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buysite/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.urls import reverse
from pytils.translit import slugify

#Статус покупки
STATUS = (
    ('Buy', 'Куплено'),
    ('Planned', 'Запланировано'),
)

#Признак расчета
OPERTYPE = (
    (1, 'Приход'),
    (2, 'Возврат прихода'),
    (3, 'Расход'),
    (4, 'Возврат расхода'),
)

#Применяемая система налогообложения
    #«1» — общая система налогообложения;
    #«2» — упрощенная система налогообложения (доход);
    #«4» — упрощенная система налогообложения (доход минус расход);
    #«8» — единый налог на вмененный доход;
    #«16» — единый сельскохозяйственный налог;
    #«32» — патентная система налогообложения. 
TAXTAPE = (
    (1, 'ОСН'),
    (2, 'УСН доход'),
    (4, 'УСН доход - Расход'),
    (8, 'ЕНВД'),
    (16, 'ЕСХН'),    
    (32, 'Патент'),    
)

#Ставка НДС:
NDSRATE = (
    ('1', 'НДС 20%'),
    ('2', 'НДС 10%'),
    ('3', 'НДС 20/120'),
    ('4', 'НДС 10/110'),
    ('5', 'НДС 0%'),    
    ('6', 'НДС не облагается'),    
)

class Сategory(models.Model):
    #Справочник/Группы продуктов
    name = models.CharField(max_length=20, unique=True, verbose_name='Категория')
    slug = models.SlugField(unique=True, verbose_name='slug')
    comment = models.CharField(max_length=250, blank=True, verbose_name='Комментарий')
    
    def get_absolute_url(self):
        return reverse('category', kwargs={'category_slug': self.slug})
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Сategory, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name='Категория товаров'
        verbose_name_plural = 'Категория товаров'

class Measure(models.Model):
    #Справочник/Единица измерения
    name = models.CharField(max_length=100, unique=True, verbose_name='Единица измерения')  
    name_mini = models.CharField(max_length=100, unique=True, verbose_name='Единица измерения(сокр.)')  
    slug = models.CharField(max_length=20, unique=True, verbose_name='slug')
    
    def __str__(self):
        return self.name_mini
    
    class Meta:
        verbose_name='Единица измерения'
        verbose_name_plural = 'Единица измерения'
        

class Group(models.Model):
    #Продукт
        #name               Название товарной позиции
        #slug               Slug
        #category           Группа товаров(class Сategory)
        #measure            Единица измерения
        #expiration_date    Срок годности
        #comment            Комментарий
    
    name = models.CharField(max_length=250, verbose_name='Наименование')
    slug = models.SlugField(unique=True, verbose_name='slug')
    category = models.ForeignKey(Сategory, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Категория')
    measure = models.ForeignKey(Measure, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Единица измерения')
    comment = models.CharField(max_length=250, blank=True, verbose_name='Комментарий')
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('group', kwargs={'group_slug': self.slug})
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Group, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name='Статус'
        verbose_name_plural = 'Статус'
    
class Ticket (models.Model):
    #Чек
        #json           json от ФНС
        #qr             qr Code
        #operationType  Признак расчета    
        #datetime       Дата/Время
        #datetimeunix   Дата(unix)
        #totalsum       Общая сумма
        #cashTotalSum   Сумма, уплаченная наличными в рублях.
        #ecashTotalSum  Сумма, уплаченная безналичными, в рублях.
        #taxationType   Система налогообложения
        #internetSign   Признак расчетов в Интернете
        #fd             Порядковый номер фискального документа(fiscaldocumentnumber)
        #fn             Номер фискального накопителя(fiscaldrivenumber)
        #fp             Фискальный признак документа(fiscalsign)
        #kkt            Регистрационнай номер кассового аппарата(kktregid)
        #requestNumber  Номер чека за смену
        #operator       Кассир
        #shiftnumber    Номер смены
        #retailplace    Место расчетов
        #seller_name    Наименование продавца
        #seller_inn     ИНН продавца
    
    json = models.JSONField(blank=True, null=True, verbose_name='json от ФНС')
    qr = models.CharField(max_length=300, blank=True, null=True, verbose_name='qr')
    operationType = models.PositiveIntegerField(choices=OPERTYPE, verbose_name='Признак расчета')
    datetime = models.DateTimeField(verbose_name='Дата')
    totalsum = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Сумма')
    cashTotalSum = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name='Наличными')
    ecashTotalSum = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name='БезНаличными')
    taxationType = models.PositiveIntegerField(blank=True, null=True, choices=TAXTAPE, verbose_name='Вид налогообложения')
    internetSign = models.BooleanField(blank=True, null=True, default=False, verbose_name='Через Интернет')
    fd = models.PositiveBigIntegerField(verbose_name='ФД')
    fn = models.PositiveBigIntegerField(verbose_name='ФН')
    fp = models.PositiveBigIntegerField(verbose_name='ФП')
    kkt = models.PositiveBigIntegerField(verbose_name='ККТ')
    requestNumber = models.PositiveBigIntegerField(verbose_name='Номер чека')
    operator = models.CharField(max_length=100, blank=True, null=True, verbose_name='Кассир')
    shiftnumber = models.CharField(max_length=30,blank=True, null=True, verbose_name='Номер смены')
    retailplace = models.CharField(max_length=300, blank=True, null=True, verbose_name='Место расчетов')
    user = models.CharField(max_length=300, blank=True, null=True, verbose_name='Наименование продавца')
    userInn = models.CharField(max_length=12,blank=True, null=True, verbose_name='ИНН продавца')

    def __str__(self):
        return str(self.fp)
    
    def get_absolute_url(self):
        return reverse('ticket', kwargs={'fp': self.fp})
    
    def datestr(self):
        return str(self.datetime.strftime('%d.%m.%Y'))

class Seller(models.Model):
    #Продавец
        #name       Наименование
        #slug       Slug
        #inn        ИНН
        #place      Где расположен
        #comment    Комментарий
    
    name = models.CharField(max_length=250, unique=True, verbose_name='Продавец')
    slug = models.CharField(max_length=20, unique=True, verbose_name='slug')
    inn = models.PositiveBigIntegerField(blank=True,verbose_name='ИНН')
    place = models.CharField(max_length=300, blank=True, verbose_name='Адрес')
    comment = models.CharField(max_length=250, blank=True, verbose_name='Комментарий')

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name='Продавец'
        verbose_name_plural = 'Продавец'

class Buy(models.Model):
    #Покупка товара
        #name            Наименовение
        #state           Состояние(BuyState)
        #dateTime        Дата/время покупки
        #price           Цена
        #quantity        Колличество
        #measure         Единица измерения
        #sum             Сумма
        #group           Группа товаров(class Group)
        #user            Покупатель(class user)
        #seller          Продавец(class Seller)
        #ticket          Чек(class Ticket)
        #nds             Ставка НДС
        #ndsSum          Сумма НДС
        #productType     Признак предмета расчета
        #paymentType     Признак способа расчета
        #comment         Комментарий
        
    name = models.CharField(max_length=300, verbose_name='Наименование')
    state = models.CharField(max_length=32, choices=STATUS, default='Buy', verbose_name='Status')
    dateTime = models.DateTimeField(verbose_name='Дата/время')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quantity = models.DecimalField(max_digits=6, decimal_places=3, verbose_name='Количество')
    measure = models.ForeignKey(Measure, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Единица измерения')
    sum = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Сумма')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Группа')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Покупатель')
    seller = models.ForeignKey(Seller, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Продавец')
    ticket = models.ForeignKey(Ticket, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Чек')
    nds = models.CharField(choices=NDSRATE,max_length = 2, null=True, blank=True, verbose_name='Ставка НДС')
    ndsSum = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, verbose_name='Сумма НДС')
    productType = models.CharField(max_length=10,null=True, blank=True, verbose_name='Предмета расчета')
    paymentType = models.CharField(max_length=10,null=True, blank=True, verbose_name='Способа расчета')
    comment = models.CharField(max_length=250, null=True, blank=True, verbose_name='Комментарий')
    
    def __str__(self):
        return self.name
    
    def datestr(self):
        return str(self.dateTime.strftime('%d.%m.%Y'))
    
class Profile(models.Model):
    #Расширение свойст пользователя(связана с user)
    #user           user
    #slug           slug
    #tel            Телефон
    #session_id     id сесси после аунтификации(Для ФНС)
    #session_date   Дата последнего получения session_id(Для ФНС)
    #refresh_token  Токен для обновления сессии(Для ФНС)
    #device_os      Какое устройство(Для ФНС)

buysite/forms.py
from datetime import datetime, date, time, timedelta
from pyexpat import model
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Buy, Group

class AddQRDetailForm(forms.Form):
    #Форма для проверки чека по реквизитам
    fn = forms.IntegerField(required=True, label='ФН', initial=9960440301303377, widget=forms.NumberInput(attrs={'class':'fn', 'placeholder':'Номер фискального накопителя', 'autocomplete':'off', 'maxlength': '16'}))
    fd = forms.IntegerField(required=True, label='ФД', initial=21631, widget=forms.NumberInput(attrs={'class':'fd', 'placeholder':'Номер фискального документа', 'autocomplete':'off', 'maxlength': '16'}))
    fp = forms.IntegerField(required=True, label='ФП', initial=2641149654, widget=forms.NumberInput(attrs={'class':'fp', 'placeholder':'Фискальный признак документа', 'autocomplete':'off', 'maxlength': '16'}))
    sum = forms.DecimalField(max_digits=16, decimal_places=2, required=True, label='ИТОГО', initial=1303.13, widget=forms.NumberInput(attrs={'class':'sum', 'placeholder':'Сумма чека', 'autocomplete':'off', 'maxlength': '16'}))
    date = forms.DateField(required=True, label='ДАТА', initial=date(2022, 4, 1), widget=forms.TextInput(attrs={'type':'date'}))
    time = forms.TimeField(required=True, label='ВРЕМЯ', initial=time(18, 45), widget=forms.TextInput(attrs={'type':'time'}))
    type = forms.ChoiceField(required=True, label='Признак расчета', choices=((1, "Приход"), (2, "Возврат прихода"), (3, "Расход"), (4, "Возврат расхода")))
    tel = forms.CharField(required=True, label='ТЕЛЕФОН', initial='+7', widget=forms.NumberInput(attrs={'class':'tel', 'placeholder':'89008000101', 'autocomplete':'off', 'maxlength': '12'}))
    save = forms.BooleanField(required=False, label='Сохранить', initial=True)

class AddQRLineForm(forms.Form):
    #Форма для проверки чека по строке
    QRLine = forms.CharField(required=True, label='Строка из QR-кода', initial='t=20220522T122300&s=306.00&fn=9960440300624942&i=125520&fp=3008505265&n=1\n\
t=20220520T1425&s=1299.68&fn=9282440300755301&i=160137&fp=2243882731&n=1', widget=forms.Textarea(attrs={'placeholder':"Содержимое QR-кода", 'rows':"6", 'autocomplete':'off'}))
    tel = forms.CharField(required=True, label='ТЕЛЕФОН', initial='+7', widget=forms.NumberInput(attrs={'class':'tel', 'placeholder':'89008000101', 'autocomplete':'off', 'maxlength': '12'}))
    save = forms.BooleanField(required=False, label='Сохранить', initial=True)

class AddQRFileForm(forms.Form):
    #Форма для проверки чека по файлу
    file = forms.FileField(label = "Файл")
    save = forms.BooleanField(required=False, label='Сохранить', initial=True)
    
class SendSMSForm(forms.Form):
    #Форма для получения кода из смс
    sms = forms.IntegerField(required=True, label='Код из смс', widget=forms.NumberInput(attrs={'class':'sms', 'autofocus': 'autofocus', 'maxlength': '7'}))

class AddBuyForm(forms.ModelForm):
    #Форма для добавления покупок
    class Meta:
        model = Buy
        fields = ('name', 'state', 'dateTime', 'price', 'quantity', 'measure', 'group', 'comment', 'user')
        widgets = {
            'dateTime': forms.TextInput(attrs={'type':'datetime-local'}),
        }
        
class AddGroupForm(forms.ModelForm):
    #Форма для добавления групп товаров
    class Meta:
        model = Group
        fields = ('name', 'category', 'measure', 'comment')

class AddPersonalForm(forms.Form):
    #Форма фильтра личного кабинета
    dateFrom = forms.DateField(required=True, label='ДАТА', widget=forms.TextInput(attrs={'type':'date','width':'20px'}))
    dateBy = forms.DateField(required=True, label='-', widget=forms.TextInput(attrs={'type':'date'}))

class LoginForm(forms.Form):
    #Форма для авторизации
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    #Форма для регистрации пользователей
    password = forms.CharField(label='Придумайте пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Пароль еще раз', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username',)

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return cd['password2']
    
class ProfileRegistrationForm(forms.ModelForm):
    #Форма для регистрации пользователей
    class Meta:
        model = Profile
        fields = ('tel',)


class UserEditForm(forms.ModelForm):
    #Форма для редактирования пользователя
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    #Форма для редактирования пользователя
    class Meta:
        model = Profile
        fields = ('tel','device_os','client_version','device_id','user_agent','client_secret','os')
        
class LoginForm(forms.Form):
    #Форма входа пользователя
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
        
    

buysite/templates/buysite/addbuy.html
{% extends 'buysite/base.html' %}
{% block content %}
<div class="account">
    <h1>Добавление покупки</h1>
    <form action="{% url 'addbuy' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ BuyForm.non_field_errors }}</div>

        {% for f in BuyForm %}
            {% if f != BuyForm.user %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
            {% endif %}
        {% endfor %}

        <p><input type="submit" value="Добавить"></p>
    </form>
</div>
{% endblock %}

buysite/templates/buysite/addgroup.html
{% extends 'buysite/base.html' %}
{% block content %}
<div class="account">
    <h1>Добавление группы товаров</h1>
    <form action="{% url 'addgroup' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ GroupForm.non_field_errors }}</div>

        {% for f in GroupForm %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><input type="submit" value="Добавить"></p>
    </form>

{% endblock %}

buysite/templates/buysite/category.html
{% extends 'buysite/base.html' %}
{% block content %}
              <div class="group">
                <div class="group__head border-bottom">
                  <h2>{{ category.name }}</h2>
                </div>
                <div>
                  <div class="group__param">
                    <div class="group__param__name">Комментарий:</div>
                    <div class="group__param__value">{{ category.comment }}</div>
                  </div>
                </div>
                <div class="group__namelink">
                  <h2>Связанные названия товаров:</h2>
                  <details>
                    <summary>
                      Показать
                    </summary>
                    <ul>
                      {% for name in namelink %}
                        <li>{{ name.name }}</li>
                      {% endfor %}
                    </ul>
                  </details>
                </div>
                <div class="group__story">
                  <div class="group__story__haed">
                    <h2>История покупок:</h2>
                  </div>
                  <div class="filter">
                    <form action="" method="post">
                    {% csrf_token %}
                      <div class="filter__body">
                        {% if page_obj %}
                          {% for buy in page_obj %}
                          <div class="fbuy">
                            <div class="fbuy__name">
                              {{ buy.name }}
                              {% if buy.comment %}
                                &#91; {{ buy.comment }} &#93;
                              {% endif %}
                              <div class="fbuy__btn" >
                                <button name = "edit" value="{{buy.pk}}">
                                  <img src="/static/buysite/images/edit.svg" alt="" width="16" height="16">
                                </button>
                              {% if buy.ticket.fp %}
                                <a href= "{{buy.ticket.get_absolute_url}}" ><img src="/static/buysite/images/ticket.svg" alt="" width="16" height="16"></a>
                              {% endif %}
                              <button name = "del" value="{{buy.pk}}">
                                <img src="/static/buysite/images/del.svg" alt="" width="16" height="10">
                              </button>
                            </div>
                          </div>
                            <div class="fbuy__params">
  
                              <div class="fbuy__param">
                                {% if buy.group %}
                                  <div class="fbuy__param__name">Категория:</div>
                                  <div class="fbuy__param__value">{{ buy.group.category }}</div>
                                {% else %}
                                  <div class="fbuy__param__name">Категория:</div>
                                  <div class="fbuy__param__value">Пусто</div>
                                {% endif %}
                              </div>
  
                              <div class="fbuy__param">
                                {% if buy.group %}
                                  <div class="fbuy__param__name">Группа:</div>
                                  <div class="fbuy__param__value"><a href="{% url "group" buy.group.slug %}">{{ buy.group }}</a></div>
                                {% else %}
                                  <div class="fbuy__param__name">Группа:</div>
                                  <div class="fbuy__param__value">Пусто</div>
                                {% endif %}
                              </div>
  
                              <div class="fbuy__param">
                                  <div class="fbuy__param__name">Статус:</div>
                                  <div class="fbuy__param__value">{{ buy.get_state_display }}</div>
                              </div>
  
                              <div class="fbuy__param">
                                <div class="fbuy__param__name">Дата:</div>
                                <div class="fbuy__param__value">{{ buy.datestr }}</div>
                              </div>
  
                              <div class="fbuy__param">
                                <div class="fbuy__param__name">Цена:</div>
                                <div class="fbuy__param__value">{{ buy.price }}</div>
                              </div>
  
                              <div class="fbuy__param">
                                <div class="fbuy__param__name">Колличество:</div>
                                <div class="fbuy__param__value">{{ buy.quantity }}</div>
                              </div>
  
                              <div class="fbuy__param">
                                <div class="fbuy__param__name">Сумма:</div>
                                <div class="fbuy__param__value">{{ buy.sum }}</div>
                              </div>
                            </div>
                          </div>
                          {% endfor %}
                        {% else %}
                          Ничего не найдено
                        {% endif %}
                        {% if page_obj.paginator.count > 1 %}
                        <ul class="pagination">
                          <li>
                            <a href="{{prev_page_url}}" {% if prev_page_url %} class="active_nav" {% endif %}>&laquo;</a>
                          </li>
                          {% for page in page_obj.paginator.page_range %}
                          {% if page_obj.number == page %}
                          <li>
                            <a href="?page={{page}}" class="active_number">{{page}}</a>
                          </li>
                          {% elif page > page_obj.number|add:-3 and page < page_obj.number|add:3 %}
                          <li>
                            <a href="?page={{page}}">{{page}}</a>
                          </li>
                          {% endif %}
                          {% endfor %}
                          <li>
                            <a href="{{next_page_url}}" {% if next_page_url %} class="active_nav" {% endif %}>&raquo;</a>
                          </li>
                        </ul>
                        {% endif %}
                        {% if page_obj %}
                        <div class="filter__functions">
                          <div class="filter-btn"><input type="submit" value="Выгрузить в EXEL" name="exel"></div>
                        </div>
                        {% endif %}
                      </div>
                    </form>
                  </div>
                </div>
              </div>
{% endblock %}

buysite/templates/buysite/editbuy.html
{% extends 'buysite/base.html' %}
{% block content %}
<div class="account">
    <h1>Редактирование покупки</h1>
    <form action="{% url 'editbuy' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ BuyForm.non_field_errors }}</div>

        {% for f in BuyForm %}
            {% if f != BuyForm.user %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
            {% endif %}
        {% endfor %}
        <p><input type="submit" value="Редактировать"></p>
    </form>
</div>
{% endblock %}

buysite/templates/buysite/editgroup.html
{% extends 'buysite/base.html' %}
{% block content %}
<div class="account">
    <h1>Редактирование группы товаров</h1>

    <form action="{% url 'editgroup' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ GroupForm.non_field_errors }}</div>

        {% for f in GroupForm %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><input type="submit" value="Редактировать"></p>
    </form>
</div>
{% endblock %}

buysite/templates/buysite/ticket.html
{% extends 'buysite/base.html' %}
{% load static %}
<style type="text/css">
  @font-face {
		font-family: 'Narrow-Regular';
		src: url("{% static 'buysite//fonts/PT_Sans_Narrow/PTSansNarrow-Regular.ttf' %}") format("truetype");
		font-style: normal;
		font-weight: normal;
		}
</style>
{% block content %}
      <div class="layout-ticket">
        <div class="ticket">
          <div class="ticket__doc">
            <div class="ticket__docType">
              КАССОВЫЙ ЧЕК
            </div>
            <div class="ticket__operationType">
              {{ ticket.get_operationType_display }}
            </div>
          </div>

          <div class="ticket__buy">
            {% for b in buy %}
            <div class="buy">
              <div class="buy__subject">
                <div class="buy__name">
                  {{ b.name }}
                </div>
              </div>
              <div class="buy__options">
                <div class="buy__count">
                  {{ b.quantity }} &nbsp &#215 &nbsp
                </div>
                <div class="buy__price">
                  {{ b.price }}руб &nbsp = &nbsp
                </div>
                <div class="buy__sum">
                  <b>{{ b.sum }}руб</b>
                </div>
              </div>
            </div>
            {% endfor %}

            <div class="ticket__total">
              <div class="total__amount">
                <div>
                  <b>ИТОГО:</b>
                </div>
                <div>
                  <b>{{ ticket.totalsum }}руб</b>
                </div>
              </div>
              <div class="total__cashSum">
                <div>
                  Наличными:
                </div>
                <div>
                  {{ ticket.cashTotalSum }}руб
                </div>
              </div>
              <div class="total__ecashSum">
                <div>
                  Безналичными:
                </div>
                <div>
                  {{ ticket.ecashTotalSum }}руб
                </div>
              </div>
            </div>
            <div class="ticket__details">
              <div>
                Вид налогообложения: &nbsp {{ ticket.get_taxationType_display }}
              </div>
              <div>
                ККТ: &nbsp {{ ticket.kkt }}
              </div>
              <div>
                ФД: &nbsp {{ ticket.fd }}
              </div>
              <div>
                ФН: &nbsp {{ ticket.fn }}
              </div>
              <div>
                ФП: &nbsp {{ ticket.fp }}
              </div>
            </div>
            <div class="ticket__seller">
              <div>
                Продавец: &nbsp {{ ticket.user }}
              </div>
              <div>
                ИНН: &nbsp {{ ticket.userInn }}
              </div>
              <div>
                Место расчетов: &nbsp {{ ticket.retailplace }}
              </div>
              <div>
                Дата: &nbsp {{ ticket.datetime }}
              </div>
              <div>
                Чек: &nbsp {{ ticket.requestNumber }}
              </div>
              <div>
                Смена: &nbsp {{ ticket.shiftnumber }}
              </div>
              <div>
                Кассир: &nbsp {{ ticket.operator }}
              </div>
            </div>
            <div class="ticket__QR">
              <img src="{{ img }}">
            </div>
          </div>
        </div>
      </div>
{% endblock %}